# --- 1. IDENTIFICACAO E PORTA ---
spring.application.name=auth-service

server.port=8300

# --- 2. BANCO DE DADOS (POSTGRESQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/pecstore_auth
spring.datasource.username=postgres
spring.datasource.password=123

# --- 3. HIBERNATE / JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- 4. EUREKA CLIENT ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- 5. CONFIGURACOES DO JWT ---
api.security.token.secret=PecStoreSuperSecretKey2026MusicalInstrumentsAuthServiceToken
# Tempo de expiracao do token em horas (2 horas)
api.security.token.expiration=2