server:
  port: 8765
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"

      discovery:
        locator:
          enabled: false

      default-filters:
        - PreserveHostHeader
      forwarded-headers-strategy: native
      httpclient:
        wiretap: true
      filter:
        remove-hop-by-hop: false

      routes:
        - id: product-service-api
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/produtos/**
          filters:
            - AddRequestHeader=X-Debug, ProductRoute
            - PreserveHostHeader

        - id: order-service-api
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/pedidos/**
          filters:
            - AddRequestHeader=X-Debug, OrderRoute
            - PreserveHostHeader

        - id: product-service-docs
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v3/api-docs/product-service
          filters:
            - RewritePath=/v3/api-docs/product-service, /v3/api-docs

        - id: order-service-docs
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v3/api-docs/order-service
          filters:
            - RewritePath=/v3/api-docs/order-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Product Service
        url: /v3/api-docs/product-service
      - name: Order Service
        url: /v3/api-docs/order-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fail-fast: false
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: "minha-chave-secreta-super-longa-e-segura-para-o-desafio-123456"