server:
  port: 8765

  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # DESLIGAMOS o roteador automático para ter controle total
      discovery:
        locator:
          enabled: false

      # ⚙️ Preserva cabeçalhos sensíveis como Authorization
      default-filters:
        - PreserveHostHeader
      forwarded-headers-strategy: native
      httpclient:
        wiretap: true
      filter:
        remove-hop-by-hop: false

      # DEFINIMOS TODAS AS NOSSAS ROTAS MANUALMENTE
      routes:
        # --- Rota para a API de Produtos ---
        - id: product-service-api
          uri: lb://PRODUCT-SERVICE
          predicates:
            # A URL que o cliente usará será: /produtos
            - Path=/produtos/**
          filters:
            # (Opcional) Loga requisições para debug
            - AddRequestHeader=X-Debug, ProductRoute
            # (Opcional) Mantém o header Authorization
            - PreserveHostHeader

        # --- Rota para a API de Pedidos ---
        - id: order-service-api
          uri: lb://ORDER-SERVICE
          predicates:
            # A URL que o cliente usará será: /pedidos
            - Path=/pedidos/**
          filters:
            - AddRequestHeader=X-Debug, OrderRoute
            - PreserveHostHeader

        # --- Rota para a DOCUMENTAÇÃO de Produtos ---
        - id: product-service-docs
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v3/api-docs/product-service
          filters:
            - RewritePath=/v3/api-docs/product-service, /v3/api-docs

        # --- Rota para a DOCUMENTAÇÃO de Pedidos ---
        - id: order-service-docs
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v3/api-docs/order-service
          filters:
            - RewritePath=/v3/api-docs/order-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Product Service
        url: /v3/api-docs/product-service
      - name: Order Service
        url: /v3/api-docs/order-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    fail-fast: false
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: "minha-chave-secreta-super-longa-e-segura-para-o-desafio-123456"