# ==========================================
# 1. CONFIGURAÇÕES DO SERVIDOR E NOME
# ==========================================
server.port=8200
spring.application.name=order-service

# ==========================================
# 2. CONEXÃO COM O BANCO DE DADOS (POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5433/pecstore_pedidos
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 3. CONFIGURAÇÕES DO HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# 4. DISCOVERY SERVICE (EUREKA)
# ==========================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/